Package will be removed from package_list even if not found on system.
Signed-off-by: mvtab <mvtabilitas@protonmail.com>

diff --git a/aurx b/aurx
--- a/aurx
+++ b/aurx
@@ -142,6 +142,8 @@ remove-from-system() {
 	TARGET_PACKAGE=${1}
 	if [[ $(sudo pacman -Qi ${TARGET_PACKAGE} 2> /dev/null) ]]; then
 		sudo pacman ${REMOVE_OPTS} ${TARGET_PACKAGE}
+	elif [[ $(sudo pacman -Qi ${TARGET_PACKAGE} 2> /dev/null) == "error: package \'${TARGET_PACKAGE}\' was not found" ]]; then
+		return 0
 	else
 		return 1
 	fi
@@ -210,7 +212,7 @@ install-aur-package() {
 	compare-versions ${TARGET_PACKAGE} || ${FORCE_PROCESS} ||  return 10
 
 	clone-git-repo ${TARGET_PACKAGE} || return 11
-	
+
 	build-makepkg-package ${TARGET_PACKAGE} || return 12
 	
 	write-package-list ${TARGET_PACKAGE} || return 13
@@ -221,7 +223,7 @@ install-aur-package() {
 remove-aur-package() {
 	TARGET_PACKAGE=${1}
 
-	remove-from-system ${TARGET_PACKAGE} || return 20
+	remove-from-system ${TARGET_PACKAGE} || [[ ${?} -eq 1 ]] || return 20
 
 	remove-from-package-list ${TARGET_PACKAGE} || return 21
 
@@ -413,6 +415,7 @@ if ${PROCESS_ALL}; then
 	TARGET_PACKAGES+=$(cat ${SOURCE_PATH}/package_list 2> /dev/null)
 fi
 for SELECTED_PACKAGE in ${TARGET_PACKAGES[@]}; do
+	# Refresh sudo timestamp for less sudo prompts.
 	${CURRENT_OPERATION}-aur-package "${SELECTED_PACKAGE}" 1> ${STDOUT_DESTINATION} 2> ${STDERR_DESTINATION}
 	ERROR_CODE=${?}
 	case "${ERROR_CODE}" in
