Added metadata to aur-update.
Signed-off-by: mvtab <mvtabilitas@protonmail.com>

diff --git a/bashrc_functions b/bashrc_functions
--- a/bashrc_functions
+++ b/bashrc_functions
@@ -103,10 +103,12 @@ aur-remove() {
 
 	return 0
 }
-
 aur-update() {
-	# Work directory.
 	local SRC_PATH="${SRC_PATH:-${HOME}/.src}"
+	local PACKAGE_COUNT=$(cat ${SRC_PATH}/package_list | wc -l)
+	local UP_TO_DATE_COUNT=0
+	local UPDATED_COUNT=0
+	local ERROR_COUNT=0
 	
 	# Sanity checks.
 	if [[ ! -f ${SRC_PATH}/package_list ]] || [[ -z "$(cat ${SRC_PATH}/package_list)" ]]; then
@@ -138,14 +140,24 @@ aur-update() {
 			aur-install ${PACKAGE}
 			if [[ ${?} == 0 ]]; then
 				echo "[+] ${PACKAGE} updated."
+				((UPDATED_COUNT=UPDATED_COUNT+1))
 			else
-				echo "[-] Could not update ${PACKAGE}. Skipping."
+				echo "[-] Could not update ${PACKAGE}. Skipping." >&2
+				((ERROR_COUNT=ERROR_COUNT+1))
 			fi
 		else
 			echo "[i] ${PACKAGE} is up to date."
+			((UP_TO_DATE_COUNT=UP_TO_DATE_COUNT+1))
 		fi
 	done
-	
+
+	if [[ ${ERROR_COUNT} == 0 ]]; then
+		echo "[+] Out of ${PACKAGE_COUNT} packages, ${UPDATED_COUNT} were updated and ${UP_TO_DATE_COUNT} were up to date."
+	else
+		echo "[-] Could not install ${ERROR_COUNT} out of ${PACKAGE_COUNT} packages." >&2
+		echo "[+] ${UPDATED_COUNT} packages were updated and ${UP_TO_DATE_COUNT} were up to date."
+	fi
+
 	return 0
 }
 
